apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: dummy-pipeline
    name: dummy-pipeline
  name: dummy-pipeline-2
spec:
  triggers:
    - github:
        secret: secret102
      type: GitHub
    - generic:
        secret: secret102
      type: Generic
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent {
            label 'maven'
          }

          stages {
            stage('Stage 1') {
              steps {
                sh "echo Stage #1"
              }
            }

            stage('Stage 2') {
              steps {
                sh "echo Stage #2"
              }
            }

            stage('Stage 3') {
              steps {
                sh "echo Stage #3"
              }
            }
          }
        }
    type: JenkinsPipeline
status:
  lastVersion: 0